# Question: What is the relationship between specific post characteristics (like video duration, use of trending audio, posting time, and hashtag count) and the likelihood of a post achieving viral status on Social Media?

##TikTok statistics

What we want is meta data and engagement metrics in order to define or approximate viral status.

- Demonstrate the relevance of these sources using initial exploration, such as summary statistics.
- Brief description of downloaded data and reflection on how well it matches requirements.
- Profiling steps that should include a short description, the code to execute these, and an interpretation.
- Discussion of the quality of the data relating to aspects to be considered during data preparation and analysis.
- Concluding paragraph that summarizes suitability and important points to take note of if the dataset is selected to be used.

*** Shofo TikTok General (Small) provides comprehensive TikTok metadata including captions, hashtags, posting time, and engagement metrics.

## DS1

[Shofo TikTok General (Small) – Extracted Posts Metadata (DS1)]  
`tiktok_posts.csv`

This dataset contains TikTok post-level
metadata extracted from the Shofo TikTok General (Small) dataset.

**Strengths:**
- Contains temporal data (date/time posted), enabling analysis of posting time effects.
- Includes video duration, which is directly relevant to short-form content performance.
- Derived from a curated dataset source and structured for analysis.

**Weaknesses:**
- Some fields may require additional cleaning (e.g., timestamps, missing values).

In [ ]:
import pandas as pd

tiktok_posts = pd.read_csv("tiktok_posts.csv")
tiktok_posts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57960 entries, 0 to 57959
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   video_id         57960 non-null  int64
 1   creator          57960 non-null  object
 2   web_url          57960 non-null  object
 3   date_posted      57960 non-null  object
 4   duration_sec     57960 non-null  float64
 5   post_hour        57960 non-null  int64
 6   post_day         57960 non-null  int64
 7   is_ad            57960 non-null  bool
 8   is_ai_generated  57960 non-null  bool
dtypes: bool(2), float64(1), int64(3), object(3)
memory usage: 3.2+ MB

In [ ]:
posts = pd.read_csv("tiktok_posts.csv")
posts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57960 entries, 0 to 57959
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   video_id         57960 non-null  int64
 1   creator          57960 non-null  object
 2   web_url          57960 non-null  object
 3   date_posted      57960 non-null  object
 4   duration_sec     57960 non-null  float64
 5   post_hour        57960 non-null  int64
 6   post_day         57960 non-null  int64
 7   is_ad            57960 non-null  bool
 8   is_ai_generated  57960 non-null  bool
dtypes: bool(2), float64(1), int64(3), object(3)
memory usage: 3.2+ MB

In [ ]:
posts = pd.read_csv("tiktok_posts.csv")
posts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57960 entries, 0 to 57959
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   video_id         57960 non-null  int64
 1   creator          57960 non-null  object
 2   web_url          57960 non-null  object
 3   date_posted      57960 non-null  object
 4   duration_sec     57960 non-null  float64
 5   post_hour        57960 non-null  int64
 6   post_day         57960 non-null  int64
 7   is_ad            57960 non-null  bool
 8   is_ai_generated  57960 non-null  bool
dtypes: bool(2), float64(1), int64(3), object(3)
memory usage: 3.2+ MB

In [ ]:
posts.describe(include="all")

,video_id,creator,web_url,date_posted,duration_sec,post_hour,post_day,is_ad,is_ai_generated
count,5.796000e+04,57960,57960,57960,57960.000000,57960.000000,57960.000000,57960,57960
unique,NaN,41133,57960,57949,NaN,NaN,NaN,1,2
top,NaN,espn,https://www.tiktok.com/@kellyjunkjournals/vide...,2023-04-11 04:58:15+00:00,NaN,NaN,NaN,False,False
freq,NaN,299,1,2,NaN,NaN,NaN,57960,57770
mean,7.242002e+18,NaN,NaN,NaN,37.131697,12.935921,2.979969,NaN,NaN
std,2.349199e+17,NaN,NaN,NaN,49.078904,7.318295,1.983801,NaN,NaN
min,2.077112e+17,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN
25%,7.049725e+18,NaN,NaN,NaN,11.834000,6.000000,1.000000,NaN,NaN
50%,7.255774e+18,NaN,NaN,NaN,20.567000,15.000000,3.000000,NaN,NaN
75%,7.452501e+18,NaN,NaN,NaN,53.914500,19.000000,5.000000,NaN,NaN
max,7.596256e+18,NaN,NaN,NaN,3600.034000,23.000000,6.000000,NaN,NaN

## DS2

[Shofo TikTok General (Small) – engagement metrics (DS2) – tiktok_engagement_small.csv](https://huggingface.co/datasets/Shofo/shofo-tiktok-general-small)

This dataset contains engagement metrics for TikTok videos (e.g., play/view count, like count, comment count, share count).
These fields are used to approximate virality.

Strengths:
* Contains direct engagement measures which are usable to define viral vs non-viral.
* Allows ranking and threshold-based labeling (e.g., viral if play_count ≥ 1,000,000).

Weaknesses:
* “Virality” is not a universal definition thus thresholds are arbitary.

In [ ]:
eng = pd.read_csv("tiktok_engagement_small.csv")
eng.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   video_id    1500 non-null   int64
 1   views       1500 non-null   int64
 2   likes       1500 non-null   int64
 3   shares      1500 non-null   int64
 4   comments    1500 non-null   object
 5   comments.1  1500 non-null   int64
 6   viral       1500 non-null   int64
dtypes: int64(6), object(1)
memory usage: 82.2+ KB

In [ ]:
eng.head()

,video_id,views,likes,shares,comments,comments.1,viral
0,6816532490971352325,63775355,2838180,41197,"[{""cid"": ""6817109813550809089"", ""text"": ""ye Ka...",3462,1
1,7028648636569373958,11170118,1858449,119820,"[{""cid"": ""7028668327887700782"", ""text"": ""TRAIL...",18234,1
2,7448325474079509782,12580746,2038422,171523,"[{""cid"": ""7450064475745534726"", ""text"": ""I wan...",4115,1
3,7484195697500196103,11802998,656568,25968,"[{""cid"": ""7484943808595165960"", ""text"": ""\u101...",4116,1
4,7002430146313489669,46049047,4328002,45897,"[{""cid"": ""7003313186133836549"", ""text"": ""PUT M...",23380,1

In [ ]:
eng.describe(include="all")

,video_id,views,likes,shares,comments,comments.1,viral
count,1.500000e+03,1.500000e+03,1.500000e+03,1.500000e+03,1500,1500.000000,1500.000000
unique,NaN,NaN,NaN,NaN,1476,NaN,NaN
top,NaN,NaN,NaN,NaN,[],NaN,NaN
freq,NaN,NaN,NaN,NaN,25,NaN,NaN
mean,7.231210e+18,2.683988e+07,3.075646e+06,1.600489e+05,NaN,18667.591333,0.950000
std,2.361382e+17,2.993694e+07,2.508836e+06,3.862209e+05,NaN,26169.408205,0.218018
min,6.655638e+18,8.100000e+01,1.000000e+00,0.000000e+00,NaN,0.000000,0.000000
25%,7.037300e+18,9.806592e+06,1.489674e+06,1.446775e+04,NaN,4130.500000,1.000000
50%,7.241715e+18,1.861453e+07,2.512532e+06,5.380650e+04,NaN,10374.000000,1.000000
75%,7.446487e+18,3.421150e+07,4.059367e+06,1.568095e+05,NaN,21083.750000,1.000000
max,7.596244e+18,4.160271e+08,2.341582e+07,9.597559e+06,NaN,291872.000000,1.000000

In [ ]:
# quick check: what columns do we have?
eng.columns

Index(['video_id', 'views', 'likes', 'shares', 'comments', 'comments.1',
       'viral'],
      dtype='object')

In [ ]:
# show top videos by play/view count (column name might be play_count)
# if your column is named differently, change it here after checking eng.columns
eng.sort_values(by="views", ascending=False).head(10)

,video_id,views,likes,shares,comments,comments.1,viral
282,7211568359798803717,416027059,13069793,134498,"[{""cid"": ""7247732452964614954"", ""text"": ""yea c...",31247,1
849,7293685461497777414,337083127,5554213,49471,"[{""cid"": ""7300664360380203822"", ""text"": ""Who p...",29171,1
472,7206834493833989383,249565433,15285115,643536,"[{""cid"": ""7208550556783625003"", ""text"": ""There...",37486,1
989,7436250163313790215,239700322,11514256,1971977,"[{""cid"": ""7436837749007893304"", ""text"": ""Es ac...",163837,1
340,7527461232580775175,205407934,9859492,443721,"[{""cid"": ""7528079301951406856"", ""text"": ""mr be...",21044,1
62,7329861554189520161,202005910,3451794,37926,"[{""cid"": ""7348160524392104750"", ""text"": ""i fee...",14913,1
974,7538786096793079054,201039362,23415816,9597559,"[{""cid"": ""7540011493057856277"", ""text"": ""I ain...",111378,1
652,7203290581173275909,198126383,15088828,847452,"[{""cid"": ""7217462258821546758"", ""text"": ""o fun...",94619,1
201,7359245286134271237,186266310,11572182,57615,"[{""cid"": ""7359462570078012165"", ""text"": ""the c...",25477,1
16,7325840538282822918,181591421,6577627,365581,"[{""cid"": ""7350415990831203104"", ""text"": ""Just ...",122797,1

## DS3

[Shofo TikTok General (Small) – text features (DS3) – tiktok_text.csv](https://huggingface.co/datasets/Shofo/shofo-tiktok-general-small)

This dataset contains text fields such as the caption/description and hashtags.

Strengths:
* Captions and hashtags can be quantified and linked to engagement.
* Useful for feature engineering without needing to download raw video.

Weaknesses:
* Text fields may be missing, noisy, or multilingual.
* Hashtags may be stored as strings and require standardization.

In [ ]:
txt = pd.read_csv("tiktok_text.csv")
txt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57960 entries, 0 to 57959
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   video_id       57960 non-null  int64
 1   description    57549 non-null  object
 2   hashtags       57960 non-null  object
 3   hashtag_count  57960 non-null  int64
dtypes: int64(2), object(2)
memory usage: 1.8+ MB

In [ ]:
txt.head()

,video_id,description,hashtags,hashtag_count
0,7350916080610643231,🙏🏼 #parati #fyp #carsoftiktok #greenscreen #xy...,"[""parati""]",0
1,7596163428251749663,todo que ver 🔥 🫦😍@YsraelBarajas #ysraelbarajas...,"[""ysraelbarajas""]",0
2,7313673452668439839,lindo detalle de gerberas 🥺 🌸 #parati #mexican...,"[""parati""]",0
3,7324533804658478378,omg cant believe i met you and i loved the shi...,"[""parati""]",0
4,7278870222382075167,#parati #foryou #viraltiktok #foryoupage❤️❤️ #...,"[""parati""]",0

In [ ]:
txt.describe(include="all")

            video_id description hashtags  hashtag_count
count   5.796000e+04       57549    57960        57960.0
unique           NaN       56194    13106            NaN
top              NaN    #CapCut   ["fyp"]            NaN
freq             NaN         158     7846            NaN
mean    7.242002e+18         NaN      NaN            0.0
std     2.349199e+17         NaN      NaN            0.0
min     2.077112e+17         NaN      NaN            0.0
25%     7.049725e+18         NaN      NaN            0.0
50%     7.255774e+18         NaN      NaN            0.0
75%     7.452501e+18         NaN      NaN            0.0
max     7.596256e+18         NaN      NaN            0.0

## Merge datasets (DS1 + DS2 + DS3)

We merge on video_id to combine post metadata, engagement metrics, and text fields into one analysis table.

In [ ]:
df = posts.merge(eng, on="video_id", how="inner").merge(txt, on="video_id", how="left")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   video_id         1500 non-null   int64
 1   creator          1500 non-null   object
 2   web_url          1500 non-null   object
 3   date_posted      1500 non-null   object
 4   duration_sec     1500 non-null   float64
 5   post_hour        1500 non-null   int64
 6   post_day         1500 non-null   int64
 7   is_ad            1500 non-null   bool
 8   is_ai_generated  1500 non-null   bool
 9   views            1500 non-null   int64
 10  likes            1500 non-null   int64
 11  shares           1500 non-null   int64
 12  comments         1500 non-null   object
 13  comments.1       1500 non-null   int64
 14  viral            1500 non-null   int64
 15  description      1491 non-null   object
 16  hashtags         1500 non-null   object
 17  hashtag_count    1500 non-null   int64
dtypes: bool(2), float64(1), int64(9), object(6)
memory usage: 190.6+ KB

In [ ]:
df.head()

,video_id,creator,web_url,date_posted,duration_sec,post_hour,post_day,is_ad,is_ai_generated,views,likes,shares,comments,comments.1,viral,description,hashtags,hashtag_count
0,7596102576446147853,graciebmaee,https://www.tiktok.com/@graciebmaee/video/7596...,2026-01-16 23:18:02+00:00,19.267,23,4,False,False,2044,172,1,"[{""cid"": ""7596506328261772087"", ""text"": ""Jesus...",4,0,#fypシ #foryou #dance #bsf #trend,"[""fyp\u30b7""]",0
1,7231295965381152043,l_j8125,https://www.tiktok.com/@l_j8125/video/72312959...,2023-05-09 21:21:43+00:00,34.165,21,1,False,False,13960113,1540299,146934,"[{""cid"": ""7232209497344426798"", ""text"": ""It\u2...",21245,1,Girl I don’t even like pizza #fyp #explore #fo...,"[""fyp""]",0
2,7557815079488490807,sixfd,https://www.tiktok.com/@sixfd/video/7557815079...,2025-10-05 19:02:55+00:00,15.046,19,6,False,False,6967887,759412,19355,"[{""cid"": ""7565360409885967125"", ""text"": ""ur tr...",3896,1,#glitch #trending #viral #dance #fyp #new #leg...,"[""Glitch""]",0
3,7269497009885678853,c9char,https://www.tiktok.com/@c9char/video/726949700...,2023-08-20 20:01:10+00:00,5.718,20,6,False,False,17628596,1463832,4856,"[{""cid"": ""7269558347526619947"", ""text"": ""For p...",4298,1,pov: ? | tysm for 123k💕 | ac+rm: hubxmango | #...,"[""fyp""]",0
4,6998235538264214789,miriamfedakova,https://www.tiktok.com/@miriamfedakova/video/6...,2021-08-19 20:08:05+00:00,13.001,20,3,False,False,52344,522,4,"[{""cid"": ""7591465321929917239"", ""text"": ""seein...",43,0,#fypシ #fyping #fypage 👋🏼,"[""fyp\u30b7""]",0

## Conclusion

The Shofo TikTok General (Small) extracted CSVs are suitable for analyzing virality using engagement metrics and basic post characteristics.
The datasets provide post metadata (duration, posting time), engagement measures (play_count, likes, shares, comments), and text features (caption/hashtags), which together support feature analysis and simple predictive modelling of viral likelihood.